apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: soojin434/runners-hi-frontend:latest
          ports:
            - containerPort: 80